targets:
  compare-turnover:
    cmd: python3 main/main.py compare-turnover
  compare-tpaf:
    cmd: python3 main/main.py compare-tpaf
  sensitivity-plot:
    cmd: python3 main/main.py sensitivity-plot
  flows:
    cmd: python3 main/main.py flows
  fit:
    cmd: python3 main/main.py fit
  phi-base:
    cmd: python3 main/main.py phi-base
  debug:
    cmd: python3 main/main.py debug
