compare-turnover:
	python3 main/main.py compare-turnover
compare-tpaf:
	python3 main/main.py compare-tpaf
sensitivity-plot:
	python3 main/main.py sensitivity-plot
flows:
	python3 main/main.py flows
fit:
	python3 main/main.py fit
phi-base:
	python3 main/main.py phi-base
debug:
	python3 main/main.py debug
